# Copyright 2010 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=math3d/math3df
GOFILES=\
	vector3.go\
	vector4.go\
	matrix3.go\
	matrix4.go\
	quaternion.go\
	util.go\

include $(GOROOT)/src/Make.pkg
